---
layout: post
title: 一个让Netty作者也感到惊讶的错误
category: 原创
tags: Netty
description: 一个让Netty作者也感到惊讶的错误
---

为了表示我不是标题党，先来个截图：
![图片发自简书App](http://upload-images.jianshu.io/upload_images/10649427-90ae5f296da450d7.jpg)

Netty是Java世界里网络编程框架的明星，也是我非常喜欢和推崇的开源项目之一。但其核心的Future接口实现却犯了一个基本的逻辑错误，本文就指出了Netty中的核心Future接口在实现cancel和isDone方法时违反了约定规则的问题。

首先来看java.util.concurrent.Future#cancel方法的javadoc约定：

> After this method returns, subsequent calls to isDone will always return true.

就是说，在调用了cancel方法后，再调用isDone将永远返回true。

Netty的Future接口继承了Java的Future接口:

```public interface Future<V> extends java.util.concurrent.Future<V>```

所以在实现的时候理应遵循这一约定，但Netty截止到目前的最新版本中(4.1.21)，并没有遵循这一约定，参见下面的代码例子：

```
import io.netty.util.concurrent.GlobalEventExecutor;

import io.netty.util.concurrent.Promise;

public class DefaultPromiseIsDoneTest {

    private final Promise defaultPromise = GlobalEventExecutor.INSTANCE.newPromise();

    public static void main(String args[]) {

        DefaultPromiseIsDoneTest main = new DefaultPromiseIsDoneTest();

        main.isDoneTest();

    }

    private void isDoneTest() {

        defaultPromise.setUncancellable();

        defaultPromise.cancel(false);

        boolean isDone = defaultPromise.isDone();

        System.out.println(isDone);

    }
}
```
运行后，控制台打印的是 false。 而按照约定，应该打印true才对。

Netty其它几个实现类也没有遵循这一约定：


```
io.netty.channel.group.VoidChannelGroupFuture#isDone
io.netty.channel.VoidChannelPromise#isDone
```

我在Netty的github上提出了这个问题，得到了Netty官方的确认。

https://github.com/netty/netty/issues/7712

但由于修改会导致当前版本用户受到影响，所以Netty准备在下一个大版本中修复这一问题。

我们在异步编程，实现Future接口的时候，对cancel和isDone方法的理解很可能会依赖于直觉，而没有严格对照接口文档中约定的逻辑来实现。甚至像Netty这样的老司机也犯了大意的错误。特写出这篇文章，跟大家共勉。

具体的讨论可以参见我的stackoverflow帖子（本文开头的图片就截自下面的帖子）：

[does-netty-violate-the-contract-of-future-cancel-method](https://stackoverflow.com/questions/48792248/does-netty-violate-the-contract-of-future-cancel-method)
